[build]
command="npm run build"
functions="functions" 
[[plugins]]
package = "netlify-plugin-inline-functions-env"
    [plugins.inputs]   
        include=["CONTEXT"]
[functions]
  external_node_modules = ["stripe","@sendgrid/mail"]